/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnPresentSimpleRouteImport } from './routes/learn.present-simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentSimpleRoute = LearnPresentSimpleRouteImport.update({
  id: '/learn/present-simple',
  path: '/learn/present-simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mistakes': typeof MistakesRoute
  '/progress': typeof ProgressRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mistakes': typeof MistakesRoute
  '/progress': typeof ProgressRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mistakes': typeof MistakesRoute
  '/progress': typeof ProgressRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/mistakes' | '/progress' | '/learn/present-simple' | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mistakes' | '/progress' | '/learn/present-simple' | '/learn'
  id:
    | '__root__'
    | '/'
    | '/mistakes'
    | '/progress'
    | '/learn/present-simple'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MistakesRoute: typeof MistakesRoute
  ProgressRoute: typeof ProgressRoute
  LearnPresentSimpleRoute: typeof LearnPresentSimpleRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-simple': {
      id: '/learn/present-simple'
      path: '/learn/present-simple'
      fullPath: '/learn/present-simple'
      preLoaderRoute: typeof LearnPresentSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MistakesRoute: MistakesRoute,
  ProgressRoute: ProgressRoute,
  LearnPresentSimpleRoute: LearnPresentSimpleRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
