/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as All12RouteImport } from './routes/all-12'
import { Route as AllFutureRouteImport } from './routes/all-future'
import { Route as AllPastRouteImport } from './routes/all-past'
import { Route as AllPresentRouteImport } from './routes/all-present'
import { Route as AllTensesRouteImport } from './routes/all-tenses'
import { Route as CoordinatesRouteImport } from './routes/coordinates'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TimeMachineRouteImport } from './routes/time-machine'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareFutureRouteImport } from './routes/compare.future'
import { Route as CompareFutureContinuousRouteImport } from './routes/compare.future-continuous'
import { Route as CompareFuturePerfectRouteImport } from './routes/compare.future-perfect'
import { Route as CompareFuturePerfectContinuousRouteImport } from './routes/compare.future-perfect-continuous'
import { Route as ComparePastRouteImport } from './routes/compare.past'
import { Route as ComparePastPerfectRouteImport } from './routes/compare.past-perfect'
import { Route as ComparePastPerfectContinuousRouteImport } from './routes/compare.past-perfect-continuous'
import { Route as ComparePerfectRouteImport } from './routes/compare.perfect'
import { Route as ComparePerfectContinuousRouteImport } from './routes/compare.perfect-continuous'
import { Route as ComparePresentRouteImport } from './routes/compare.present'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnFutureContinuousRouteImport } from './routes/learn.future-continuous'
import { Route as LearnFuturePerfectRouteImport } from './routes/learn.future-perfect'
import { Route as LearnFuturePerfectContinuousRouteImport } from './routes/learn.future-perfect-continuous'
import { Route as LearnFutureSimpleRouteImport } from './routes/learn.future-simple'
import { Route as LearnPastContinuousRouteImport } from './routes/learn.past-continuous'
import { Route as LearnPastPerfectRouteImport } from './routes/learn.past-perfect'
import { Route as LearnPastPerfectContinuousRouteImport } from './routes/learn.past-perfect-continuous'
import { Route as LearnPastSimpleRouteImport } from './routes/learn.past-simple'
import { Route as LearnPresentContinuousRouteImport } from './routes/learn.present-continuous'
import { Route as LearnPresentPerfectRouteImport } from './routes/learn.present-perfect'
import { Route as LearnPresentPerfectContinuousRouteImport } from './routes/learn.present-perfect-continuous'
import { Route as LearnPresentSimpleRouteImport } from './routes/learn.present-simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const All12Route = All12RouteImport.update({
  id: '/all-12',
  path: '/all-12',
  getParentRoute: () => rootRouteImport,
} as any)
const AllFutureRoute = AllFutureRouteImport.update({
  id: '/all-future',
  path: '/all-future',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPastRoute = AllPastRouteImport.update({
  id: '/all-past',
  path: '/all-past',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPresentRoute = AllPresentRouteImport.update({
  id: '/all-present',
  path: '/all-present',
  getParentRoute: () => rootRouteImport,
} as any)
const AllTensesRoute = AllTensesRouteImport.update({
  id: '/all-tenses',
  path: '/all-tenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatesRoute = CoordinatesRouteImport.update({
  id: '/coordinates',
  path: '/coordinates',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeMachineRoute = TimeMachineRouteImport.update({
  id: '/time-machine',
  path: '/time-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFutureRoute = CompareFutureRouteImport.update({
  id: '/compare/future',
  path: '/compare/future',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFutureContinuousRoute = CompareFutureContinuousRouteImport.update({
  id: '/compare/future-continuous',
  path: '/compare/future-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFuturePerfectRoute = CompareFuturePerfectRouteImport.update({
  id: '/compare/future-perfect',
  path: '/compare/future-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareFuturePerfectContinuousRoute =
  CompareFuturePerfectContinuousRouteImport.update({
    id: '/compare/future-perfect-continuous',
    path: '/compare/future-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparePastRoute = ComparePastRouteImport.update({
  id: '/compare/past',
  path: '/compare/past',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePastPerfectRoute = ComparePastPerfectRouteImport.update({
  id: '/compare/past-perfect',
  path: '/compare/past-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePastPerfectContinuousRoute =
  ComparePastPerfectContinuousRouteImport.update({
    id: '/compare/past-perfect-continuous',
    path: '/compare/past-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparePerfectRoute = ComparePerfectRouteImport.update({
  id: '/compare/perfect',
  path: '/compare/perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePerfectContinuousRoute =
  ComparePerfectContinuousRouteImport.update({
    id: '/compare/perfect-continuous',
    path: '/compare/perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparePresentRoute = ComparePresentRouteImport.update({
  id: '/compare/present',
  path: '/compare/present',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFutureContinuousRoute = LearnFutureContinuousRouteImport.update({
  id: '/learn/future-continuous',
  path: '/learn/future-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFuturePerfectRoute = LearnFuturePerfectRouteImport.update({
  id: '/learn/future-perfect',
  path: '/learn/future-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFuturePerfectContinuousRoute =
  LearnFuturePerfectContinuousRouteImport.update({
    id: '/learn/future-perfect-continuous',
    path: '/learn/future-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnFutureSimpleRoute = LearnFutureSimpleRouteImport.update({
  id: '/learn/future-simple',
  path: '/learn/future-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPastContinuousRoute = LearnPastContinuousRouteImport.update({
  id: '/learn/past-continuous',
  path: '/learn/past-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPastPerfectRoute = LearnPastPerfectRouteImport.update({
  id: '/learn/past-perfect',
  path: '/learn/past-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPastPerfectContinuousRoute =
  LearnPastPerfectContinuousRouteImport.update({
    id: '/learn/past-perfect-continuous',
    path: '/learn/past-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnPastSimpleRoute = LearnPastSimpleRouteImport.update({
  id: '/learn/past-simple',
  path: '/learn/past-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentContinuousRoute = LearnPresentContinuousRouteImport.update({
  id: '/learn/present-continuous',
  path: '/learn/present-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentPerfectRoute = LearnPresentPerfectRouteImport.update({
  id: '/learn/present-perfect',
  path: '/learn/present-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentPerfectContinuousRoute =
  LearnPresentPerfectContinuousRouteImport.update({
    id: '/learn/present-perfect-continuous',
    path: '/learn/present-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnPresentSimpleRoute = LearnPresentSimpleRouteImport.update({
  id: '/learn/present-simple',
  path: '/learn/present-simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-12': typeof All12Route
  '/all-future': typeof AllFutureRoute
  '/all-past': typeof AllPastRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/coordinates': typeof CoordinatesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/future': typeof CompareFutureRoute
  '/compare/future-continuous': typeof CompareFutureContinuousRoute
  '/compare/future-perfect': typeof CompareFuturePerfectRoute
  '/compare/future-perfect-continuous': typeof CompareFuturePerfectContinuousRoute
  '/compare/past': typeof ComparePastRoute
  '/compare/past-perfect': typeof ComparePastPerfectRoute
  '/compare/past-perfect-continuous': typeof ComparePastPerfectContinuousRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/future-continuous': typeof LearnFutureContinuousRoute
  '/learn/future-perfect': typeof LearnFuturePerfectRoute
  '/learn/future-perfect-continuous': typeof LearnFuturePerfectContinuousRoute
  '/learn/future-simple': typeof LearnFutureSimpleRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-perfect': typeof LearnPastPerfectRoute
  '/learn/past-perfect-continuous': typeof LearnPastPerfectContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare/': typeof CompareIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-12': typeof All12Route
  '/all-future': typeof AllFutureRoute
  '/all-past': typeof AllPastRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/coordinates': typeof CoordinatesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/future': typeof CompareFutureRoute
  '/compare/future-continuous': typeof CompareFutureContinuousRoute
  '/compare/future-perfect': typeof CompareFuturePerfectRoute
  '/compare/future-perfect-continuous': typeof CompareFuturePerfectContinuousRoute
  '/compare/past': typeof ComparePastRoute
  '/compare/past-perfect': typeof ComparePastPerfectRoute
  '/compare/past-perfect-continuous': typeof ComparePastPerfectContinuousRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/future-continuous': typeof LearnFutureContinuousRoute
  '/learn/future-perfect': typeof LearnFuturePerfectRoute
  '/learn/future-perfect-continuous': typeof LearnFuturePerfectContinuousRoute
  '/learn/future-simple': typeof LearnFutureSimpleRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-perfect': typeof LearnPastPerfectRoute
  '/learn/past-perfect-continuous': typeof LearnPastPerfectContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare': typeof CompareIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-12': typeof All12Route
  '/all-future': typeof AllFutureRoute
  '/all-past': typeof AllPastRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/coordinates': typeof CoordinatesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/future': typeof CompareFutureRoute
  '/compare/future-continuous': typeof CompareFutureContinuousRoute
  '/compare/future-perfect': typeof CompareFuturePerfectRoute
  '/compare/future-perfect-continuous': typeof CompareFuturePerfectContinuousRoute
  '/compare/past': typeof ComparePastRoute
  '/compare/past-perfect': typeof ComparePastPerfectRoute
  '/compare/past-perfect-continuous': typeof ComparePastPerfectContinuousRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/future-continuous': typeof LearnFutureContinuousRoute
  '/learn/future-perfect': typeof LearnFuturePerfectRoute
  '/learn/future-perfect-continuous': typeof LearnFuturePerfectContinuousRoute
  '/learn/future-simple': typeof LearnFutureSimpleRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-perfect': typeof LearnPastPerfectRoute
  '/learn/past-perfect-continuous': typeof LearnPastPerfectContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare/': typeof CompareIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-12'
    | '/all-future'
    | '/all-past'
    | '/all-present'
    | '/all-tenses'
    | '/coordinates'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/future'
    | '/compare/future-continuous'
    | '/compare/future-perfect'
    | '/compare/future-perfect-continuous'
    | '/compare/past'
    | '/compare/past-perfect'
    | '/compare/past-perfect-continuous'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/future-continuous'
    | '/learn/future-perfect'
    | '/learn/future-perfect-continuous'
    | '/learn/future-simple'
    | '/learn/past-continuous'
    | '/learn/past-perfect'
    | '/learn/past-perfect-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-12'
    | '/all-future'
    | '/all-past'
    | '/all-present'
    | '/all-tenses'
    | '/coordinates'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/future'
    | '/compare/future-continuous'
    | '/compare/future-perfect'
    | '/compare/future-perfect-continuous'
    | '/compare/past'
    | '/compare/past-perfect'
    | '/compare/past-perfect-continuous'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/future-continuous'
    | '/learn/future-perfect'
    | '/learn/future-perfect-continuous'
    | '/learn/future-simple'
    | '/learn/past-continuous'
    | '/learn/past-perfect'
    | '/learn/past-perfect-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/all-12'
    | '/all-future'
    | '/all-past'
    | '/all-present'
    | '/all-tenses'
    | '/coordinates'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/future'
    | '/compare/future-continuous'
    | '/compare/future-perfect'
    | '/compare/future-perfect-continuous'
    | '/compare/past'
    | '/compare/past-perfect'
    | '/compare/past-perfect-continuous'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/future-continuous'
    | '/learn/future-perfect'
    | '/learn/future-perfect-continuous'
    | '/learn/future-simple'
    | '/learn/past-continuous'
    | '/learn/past-perfect'
    | '/learn/past-perfect-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  All12Route: typeof All12Route
  AllFutureRoute: typeof AllFutureRoute
  AllPastRoute: typeof AllPastRoute
  AllPresentRoute: typeof AllPresentRoute
  AllTensesRoute: typeof AllTensesRoute
  CoordinatesRoute: typeof CoordinatesRoute
  MistakesRoute: typeof MistakesRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  QuickRoute: typeof QuickRoute
  TestsRoute: typeof TestsRoute
  TimeMachineRoute: typeof TimeMachineRoute
  CompareFutureRoute: typeof CompareFutureRoute
  CompareFutureContinuousRoute: typeof CompareFutureContinuousRoute
  CompareFuturePerfectRoute: typeof CompareFuturePerfectRoute
  CompareFuturePerfectContinuousRoute: typeof CompareFuturePerfectContinuousRoute
  ComparePastRoute: typeof ComparePastRoute
  ComparePastPerfectRoute: typeof ComparePastPerfectRoute
  ComparePastPerfectContinuousRoute: typeof ComparePastPerfectContinuousRoute
  ComparePerfectRoute: typeof ComparePerfectRoute
  ComparePerfectContinuousRoute: typeof ComparePerfectContinuousRoute
  ComparePresentRoute: typeof ComparePresentRoute
  LearnFutureContinuousRoute: typeof LearnFutureContinuousRoute
  LearnFuturePerfectRoute: typeof LearnFuturePerfectRoute
  LearnFuturePerfectContinuousRoute: typeof LearnFuturePerfectContinuousRoute
  LearnFutureSimpleRoute: typeof LearnFutureSimpleRoute
  LearnPastContinuousRoute: typeof LearnPastContinuousRoute
  LearnPastPerfectRoute: typeof LearnPastPerfectRoute
  LearnPastPerfectContinuousRoute: typeof LearnPastPerfectContinuousRoute
  LearnPastSimpleRoute: typeof LearnPastSimpleRoute
  LearnPresentContinuousRoute: typeof LearnPresentContinuousRoute
  LearnPresentPerfectRoute: typeof LearnPresentPerfectRoute
  LearnPresentPerfectContinuousRoute: typeof LearnPresentPerfectContinuousRoute
  LearnPresentSimpleRoute: typeof LearnPresentSimpleRoute
  CompareIndexRoute: typeof CompareIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-12': {
      id: '/all-12'
      path: '/all-12'
      fullPath: '/all-12'
      preLoaderRoute: typeof All12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-future': {
      id: '/all-future'
      path: '/all-future'
      fullPath: '/all-future'
      preLoaderRoute: typeof AllFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-past': {
      id: '/all-past'
      path: '/all-past'
      fullPath: '/all-past'
      preLoaderRoute: typeof AllPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-present': {
      id: '/all-present'
      path: '/all-present'
      fullPath: '/all-present'
      preLoaderRoute: typeof AllPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-tenses': {
      id: '/all-tenses'
      path: '/all-tenses'
      fullPath: '/all-tenses'
      preLoaderRoute: typeof AllTensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinates': {
      id: '/coordinates'
      path: '/coordinates'
      fullPath: '/coordinates'
      preLoaderRoute: typeof CoordinatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-machine': {
      id: '/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof TimeMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/future': {
      id: '/compare/future'
      path: '/compare/future'
      fullPath: '/compare/future'
      preLoaderRoute: typeof CompareFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/future-continuous': {
      id: '/compare/future-continuous'
      path: '/compare/future-continuous'
      fullPath: '/compare/future-continuous'
      preLoaderRoute: typeof CompareFutureContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/future-perfect': {
      id: '/compare/future-perfect'
      path: '/compare/future-perfect'
      fullPath: '/compare/future-perfect'
      preLoaderRoute: typeof CompareFuturePerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/future-perfect-continuous': {
      id: '/compare/future-perfect-continuous'
      path: '/compare/future-perfect-continuous'
      fullPath: '/compare/future-perfect-continuous'
      preLoaderRoute: typeof CompareFuturePerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/past': {
      id: '/compare/past'
      path: '/compare/past'
      fullPath: '/compare/past'
      preLoaderRoute: typeof ComparePastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/past-perfect': {
      id: '/compare/past-perfect'
      path: '/compare/past-perfect'
      fullPath: '/compare/past-perfect'
      preLoaderRoute: typeof ComparePastPerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/past-perfect-continuous': {
      id: '/compare/past-perfect-continuous'
      path: '/compare/past-perfect-continuous'
      fullPath: '/compare/past-perfect-continuous'
      preLoaderRoute: typeof ComparePastPerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/perfect': {
      id: '/compare/perfect'
      path: '/compare/perfect'
      fullPath: '/compare/perfect'
      preLoaderRoute: typeof ComparePerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/perfect-continuous': {
      id: '/compare/perfect-continuous'
      path: '/compare/perfect-continuous'
      fullPath: '/compare/perfect-continuous'
      preLoaderRoute: typeof ComparePerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/present': {
      id: '/compare/present'
      path: '/compare/present'
      fullPath: '/compare/present'
      preLoaderRoute: typeof ComparePresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/future-continuous': {
      id: '/learn/future-continuous'
      path: '/learn/future-continuous'
      fullPath: '/learn/future-continuous'
      preLoaderRoute: typeof LearnFutureContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/future-perfect': {
      id: '/learn/future-perfect'
      path: '/learn/future-perfect'
      fullPath: '/learn/future-perfect'
      preLoaderRoute: typeof LearnFuturePerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/future-perfect-continuous': {
      id: '/learn/future-perfect-continuous'
      path: '/learn/future-perfect-continuous'
      fullPath: '/learn/future-perfect-continuous'
      preLoaderRoute: typeof LearnFuturePerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/future-simple': {
      id: '/learn/future-simple'
      path: '/learn/future-simple'
      fullPath: '/learn/future-simple'
      preLoaderRoute: typeof LearnFutureSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-continuous': {
      id: '/learn/past-continuous'
      path: '/learn/past-continuous'
      fullPath: '/learn/past-continuous'
      preLoaderRoute: typeof LearnPastContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-perfect': {
      id: '/learn/past-perfect'
      path: '/learn/past-perfect'
      fullPath: '/learn/past-perfect'
      preLoaderRoute: typeof LearnPastPerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-perfect-continuous': {
      id: '/learn/past-perfect-continuous'
      path: '/learn/past-perfect-continuous'
      fullPath: '/learn/past-perfect-continuous'
      preLoaderRoute: typeof LearnPastPerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-simple': {
      id: '/learn/past-simple'
      path: '/learn/past-simple'
      fullPath: '/learn/past-simple'
      preLoaderRoute: typeof LearnPastSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-continuous': {
      id: '/learn/present-continuous'
      path: '/learn/present-continuous'
      fullPath: '/learn/present-continuous'
      preLoaderRoute: typeof LearnPresentContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-perfect': {
      id: '/learn/present-perfect'
      path: '/learn/present-perfect'
      fullPath: '/learn/present-perfect'
      preLoaderRoute: typeof LearnPresentPerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-perfect-continuous': {
      id: '/learn/present-perfect-continuous'
      path: '/learn/present-perfect-continuous'
      fullPath: '/learn/present-perfect-continuous'
      preLoaderRoute: typeof LearnPresentPerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-simple': {
      id: '/learn/present-simple'
      path: '/learn/present-simple'
      fullPath: '/learn/present-simple'
      preLoaderRoute: typeof LearnPresentSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  All12Route: All12Route,
  AllFutureRoute: AllFutureRoute,
  AllPastRoute: AllPastRoute,
  AllPresentRoute: AllPresentRoute,
  AllTensesRoute: AllTensesRoute,
  CoordinatesRoute: CoordinatesRoute,
  MistakesRoute: MistakesRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  QuickRoute: QuickRoute,
  TestsRoute: TestsRoute,
  TimeMachineRoute: TimeMachineRoute,
  CompareFutureRoute: CompareFutureRoute,
  CompareFutureContinuousRoute: CompareFutureContinuousRoute,
  CompareFuturePerfectRoute: CompareFuturePerfectRoute,
  CompareFuturePerfectContinuousRoute: CompareFuturePerfectContinuousRoute,
  ComparePastRoute: ComparePastRoute,
  ComparePastPerfectRoute: ComparePastPerfectRoute,
  ComparePastPerfectContinuousRoute: ComparePastPerfectContinuousRoute,
  ComparePerfectRoute: ComparePerfectRoute,
  ComparePerfectContinuousRoute: ComparePerfectContinuousRoute,
  ComparePresentRoute: ComparePresentRoute,
  LearnFutureContinuousRoute: LearnFutureContinuousRoute,
  LearnFuturePerfectRoute: LearnFuturePerfectRoute,
  LearnFuturePerfectContinuousRoute: LearnFuturePerfectContinuousRoute,
  LearnFutureSimpleRoute: LearnFutureSimpleRoute,
  LearnPastContinuousRoute: LearnPastContinuousRoute,
  LearnPastPerfectRoute: LearnPastPerfectRoute,
  LearnPastPerfectContinuousRoute: LearnPastPerfectContinuousRoute,
  LearnPastSimpleRoute: LearnPastSimpleRoute,
  LearnPresentContinuousRoute: LearnPresentContinuousRoute,
  LearnPresentPerfectRoute: LearnPresentPerfectRoute,
  LearnPresentPerfectContinuousRoute: LearnPresentPerfectContinuousRoute,
  LearnPresentSimpleRoute: LearnPresentSimpleRoute,
  CompareIndexRoute: CompareIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
