/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllPresentRouteImport } from './routes/all-present'
import { Route as AllTensesRouteImport } from './routes/all-tenses'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TimeMachineRouteImport } from './routes/time-machine'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as ComparePerfectRouteImport } from './routes/compare.perfect'
import { Route as ComparePerfectContinuousRouteImport } from './routes/compare.perfect-continuous'
import { Route as ComparePresentRouteImport } from './routes/compare.present'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnPastContinuousRouteImport } from './routes/learn.past-continuous'
import { Route as LearnPastSimpleRouteImport } from './routes/learn.past-simple'
import { Route as LearnPresentContinuousRouteImport } from './routes/learn.present-continuous'
import { Route as LearnPresentPerfectRouteImport } from './routes/learn.present-perfect'
import { Route as LearnPresentPerfectContinuousRouteImport } from './routes/learn.present-perfect-continuous'
import { Route as LearnPresentSimpleRouteImport } from './routes/learn.present-simple'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllPresentRoute = AllPresentRouteImport.update({
  id: '/all-present',
  path: '/all-present',
  getParentRoute: () => rootRouteImport,
} as any)
const AllTensesRoute = AllTensesRouteImport.update({
  id: '/all-tenses',
  path: '/all-tenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeMachineRoute = TimeMachineRouteImport.update({
  id: '/time-machine',
  path: '/time-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePerfectRoute = ComparePerfectRouteImport.update({
  id: '/compare/perfect',
  path: '/compare/perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePerfectContinuousRoute =
  ComparePerfectContinuousRouteImport.update({
    id: '/compare/perfect-continuous',
    path: '/compare/perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparePresentRoute = ComparePresentRouteImport.update({
  id: '/compare/present',
  path: '/compare/present',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPastContinuousRoute = LearnPastContinuousRouteImport.update({
  id: '/learn/past-continuous',
  path: '/learn/past-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPastSimpleRoute = LearnPastSimpleRouteImport.update({
  id: '/learn/past-simple',
  path: '/learn/past-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentContinuousRoute = LearnPresentContinuousRouteImport.update({
  id: '/learn/present-continuous',
  path: '/learn/present-continuous',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentPerfectRoute = LearnPresentPerfectRouteImport.update({
  id: '/learn/present-perfect',
  path: '/learn/present-perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPresentPerfectContinuousRoute =
  LearnPresentPerfectContinuousRouteImport.update({
    id: '/learn/present-perfect-continuous',
    path: '/learn/present-perfect-continuous',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnPresentSimpleRoute = LearnPresentSimpleRouteImport.update({
  id: '/learn/present-simple',
  path: '/learn/present-simple',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare/': typeof CompareIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare': typeof CompareIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-present': typeof AllPresentRoute
  '/all-tenses': typeof AllTensesRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/quick': typeof QuickRoute
  '/tests': typeof TestsRoute
  '/time-machine': typeof TimeMachineRoute
  '/compare/perfect': typeof ComparePerfectRoute
  '/compare/perfect-continuous': typeof ComparePerfectContinuousRoute
  '/compare/present': typeof ComparePresentRoute
  '/learn/past-continuous': typeof LearnPastContinuousRoute
  '/learn/past-simple': typeof LearnPastSimpleRoute
  '/learn/present-continuous': typeof LearnPresentContinuousRoute
  '/learn/present-perfect': typeof LearnPresentPerfectRoute
  '/learn/present-perfect-continuous': typeof LearnPresentPerfectContinuousRoute
  '/learn/present-simple': typeof LearnPresentSimpleRoute
  '/compare/': typeof CompareIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-present'
    | '/all-tenses'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/past-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-present'
    | '/all-tenses'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/past-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/all-present'
    | '/all-tenses'
    | '/mistakes'
    | '/practice'
    | '/progress'
    | '/quick'
    | '/tests'
    | '/time-machine'
    | '/compare/perfect'
    | '/compare/perfect-continuous'
    | '/compare/present'
    | '/learn/past-continuous'
    | '/learn/past-simple'
    | '/learn/present-continuous'
    | '/learn/present-perfect'
    | '/learn/present-perfect-continuous'
    | '/learn/present-simple'
    | '/compare/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllPresentRoute: typeof AllPresentRoute
  AllTensesRoute: typeof AllTensesRoute
  MistakesRoute: typeof MistakesRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  QuickRoute: typeof QuickRoute
  TestsRoute: typeof TestsRoute
  TimeMachineRoute: typeof TimeMachineRoute
  ComparePerfectRoute: typeof ComparePerfectRoute
  ComparePerfectContinuousRoute: typeof ComparePerfectContinuousRoute
  ComparePresentRoute: typeof ComparePresentRoute
  LearnPastContinuousRoute: typeof LearnPastContinuousRoute
  LearnPastSimpleRoute: typeof LearnPastSimpleRoute
  LearnPresentContinuousRoute: typeof LearnPresentContinuousRoute
  LearnPresentPerfectRoute: typeof LearnPresentPerfectRoute
  LearnPresentPerfectContinuousRoute: typeof LearnPresentPerfectContinuousRoute
  LearnPresentSimpleRoute: typeof LearnPresentSimpleRoute
  CompareIndexRoute: typeof CompareIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-present': {
      id: '/all-present'
      path: '/all-present'
      fullPath: '/all-present'
      preLoaderRoute: typeof AllPresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-tenses': {
      id: '/all-tenses'
      path: '/all-tenses'
      fullPath: '/all-tenses'
      preLoaderRoute: typeof AllTensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-machine': {
      id: '/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof TimeMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/perfect': {
      id: '/compare/perfect'
      path: '/compare/perfect'
      fullPath: '/compare/perfect'
      preLoaderRoute: typeof ComparePerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/perfect-continuous': {
      id: '/compare/perfect-continuous'
      path: '/compare/perfect-continuous'
      fullPath: '/compare/perfect-continuous'
      preLoaderRoute: typeof ComparePerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/present': {
      id: '/compare/present'
      path: '/compare/present'
      fullPath: '/compare/present'
      preLoaderRoute: typeof ComparePresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-continuous': {
      id: '/learn/past-continuous'
      path: '/learn/past-continuous'
      fullPath: '/learn/past-continuous'
      preLoaderRoute: typeof LearnPastContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/past-simple': {
      id: '/learn/past-simple'
      path: '/learn/past-simple'
      fullPath: '/learn/past-simple'
      preLoaderRoute: typeof LearnPastSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-continuous': {
      id: '/learn/present-continuous'
      path: '/learn/present-continuous'
      fullPath: '/learn/present-continuous'
      preLoaderRoute: typeof LearnPresentContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-perfect': {
      id: '/learn/present-perfect'
      path: '/learn/present-perfect'
      fullPath: '/learn/present-perfect'
      preLoaderRoute: typeof LearnPresentPerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-perfect-continuous': {
      id: '/learn/present-perfect-continuous'
      path: '/learn/present-perfect-continuous'
      fullPath: '/learn/present-perfect-continuous'
      preLoaderRoute: typeof LearnPresentPerfectContinuousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/present-simple': {
      id: '/learn/present-simple'
      path: '/learn/present-simple'
      fullPath: '/learn/present-simple'
      preLoaderRoute: typeof LearnPresentSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllPresentRoute: AllPresentRoute,
  AllTensesRoute: AllTensesRoute,
  MistakesRoute: MistakesRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  QuickRoute: QuickRoute,
  TestsRoute: TestsRoute,
  TimeMachineRoute: TimeMachineRoute,
  ComparePerfectRoute: ComparePerfectRoute,
  ComparePerfectContinuousRoute: ComparePerfectContinuousRoute,
  ComparePresentRoute: ComparePresentRoute,
  LearnPastContinuousRoute: LearnPastContinuousRoute,
  LearnPastSimpleRoute: LearnPastSimpleRoute,
  LearnPresentContinuousRoute: LearnPresentContinuousRoute,
  LearnPresentPerfectRoute: LearnPresentPerfectRoute,
  LearnPresentPerfectContinuousRoute: LearnPresentPerfectContinuousRoute,
  LearnPresentSimpleRoute: LearnPresentSimpleRoute,
  CompareIndexRoute: CompareIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
